import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"

[keyboard]
bindings = [
   { key= "Right", mods= "Command", chars= "\u001BF" },
   { key= "Left",  mods= "Command", chars= "\u001BB" },
   { key= "A", mods = "Command", chars="\u0001" }
]

